# Please update this file per your vSphere environment.

azs:
- name: az-1
  cloud_properties:
    datacenters:
    - name: Datacenter
      clusters:
      - {compute: {}}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.112.123.0/24
    gateway: 10.112.123.253
    dns: [10.117.0.1]
    az: az-1
    static:
    - 10.112.123.31
    reserved:
    - 10.112.123.1-10.112.123.30
    - 10.112.123.40-10.112.123.255
    cloud_properties:
      name: VM Network

vm_types:
- name: standard
  cloud_properties:
    cpu: 1
    ram: 4_096
    disk: 81_920
    datastores: [Datastore, datastore1]
    datacenters:
    - name: Datacenter
      clusters:
      - compute: {}

disk_types:
- name: 20G
  disk_size: 20_480
  cloud_properties:
    datastores: ['Datastore', 'datastore1']

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  vm_type: standard
  az: az-1

