# This manifest contains uaa auth config and standalone errand job instance.
---
name: harbor-deployment

releases:
- name: harbor-container-registry
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: harbor-app
  azs: [az-1]
  instances: 1
  jobs:
  - name: harbor
    release: harbor-container-registry
    properties:
      hostname: ((hostname))
      db_password: ((harbor_db_password))
      admin_password: ((harbor_admin_password))
      clair_db_password: ((clair_db_password))
      with_clair: true
      with_notary: true
      ssl:
        cert: ((harbor_ssl.certificate))
        key: ((harbor_ssl.private_key))
        ca: ((default_ca.certificate))
      auth_mode: "uaa_auth"
      uaa:
        url: "https://uaa.server.local/uaa"
        client_id: "harbor_uaa_client"
        client_secret: ((harbor_uaa_client_secret))
        verify_cert: false
        admin:
          client_id: "admin"
          client_secret: "secret"

  - name: uaa-deregistration
    release: harbor-container-registry
    properties: {}
    consumes:
      harbor_uaa_reference: {from: harbor_uaa}

  - name: docker
    release: harbor-container-registry

  stemcell: default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  persistent_disk: 20480
  networks:
  - name: deployment-network

- name: testing
  azs: [az-1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: smoke-test
    release: harbor-container-registry
    properties: {}
    consumes:
      harbor_reference: {from: harbor}

  stemcell: default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  persistent_disk: 20480
  networks:
  - name: deployment-network

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000

variables:
- name: harbor_admin_password
  type: password
- name: clair_db_password
  type: password
- name: harbor_db_password
  type: password
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: harbor-ca
- name: harbor_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((hostname))
    alternative_names: [((hostname))]
