releases:
- name: harbor-container-registry
  version: 0+dev.2
addons:
- name: harbor-bosh-dns
  jobs:
  - name: harbor-dns-aliases
    release: harbor-container-registry
    properties:
      aliases:
        # 'harbor.local' must be the Harbor FQDN specified by the user.
        harbor.local:
        - "*.harbor-app.deployment-network.harbor-deployment.bosh"
        uaa.server.local:
        - "*.uaa-app.deployment-network.uaa-deployment.bosh"
- name: enable-bosh-dns
  jobs:
  - name: enable-bosh-dns
    release: harbor-container-registry
  include:
    deployments:
    - harbor-deployment
