#Availablity zones
azs:
- name: az1
  cloud_properties:
    datacenters:
    - name: Datacenter
      clusters:
      - {compute: {}}

#Networks
networks:
- name: default
  type: manual
  subnets:
  - range: 10.112.122.0/23
    gateway: 10.112.123.253
    az: az1
    static:
    - 10.112.122.1
    reserved:
    - 10.112.123.1-10.112.123.53
    - 10.112.123.57-10.112.123.255
    cloud_properties:
      name: VM Network

#VM types
vm_types:
- name: standard
  cloud_properties:
    cpu: 1
    ram: 4_096
    disk: 81_920
    datastores: [Datastore, datastore1]
    datacenters:
    - name: Datacenter
      clusters:
      - compute: {}

#Disk Types
disk_types:
- name: 20G
  disk_size: 20_480
  cloud_properties:
    datastores: ['Datastore', 'datastore1']

#Compilation
compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  vm_type: standard
  az: az1